/**************************
***** Compiler Parameters *****
***************************
@P EffectName: InstancedMeshTangentStreamOut_DrawFX
***************************
******  Resources    ******
***************************
@R    InstanceWorld_id0 => InstanceWorldBuffer.InstanceWorld [Stage: Vertex, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    InstancedMeshTangentStreamOut_DrawFX => 18c1fa65b877749a9b08637d944bb2eb
@S    InstanceWorldBuffer => 118f96430a4a97f2d69bc74f02ce134e
***************************
*****     Stages      *****
***************************
@G    Vertex => 728c0dbb1b1488df38b67c1ad2536e21
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// Resource bind info for InstanceWorld_id0
// {
//
//   struct InstanceTransform
//   {
//       
//       float4x4 Matrix;               // Offset:    0
//
//   } $Element;                        // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// InstanceWorld_id0                 texture  struct         r/o             t0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_InstanceID            0   x           0   INSTID    uint   x   
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TANGENT                  0   xyzw        3     NONE   float   xyzw
// TEXCOORD                 0   xy          4     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_structured t0, 64
dcl_input_sgv v0.x, instance_id
dcl_input v1.xyz
dcl_input v2.xyz
dcl_input v3.xyzw
dcl_input v4.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xyz
dcl_output o2.xyzw
dcl_output o3.xy
dcl_temps 4
//
// Initial variable locations:
//   v0.x <- __input__.InstanceID_id1; 
//   v1.x <- __input__.Position_id3.x; v1.y <- __input__.Position_id3.y; v1.z <- __input__.Position_id3.z; 
//   v2.x <- __input__.Normal_id4.x; v2.y <- __input__.Normal_id4.y; v2.z <- __input__.Normal_id4.z; 
//   v3.x <- __input__.Tangent_id5.x; v3.y <- __input__.Tangent_id5.y; v3.z <- __input__.Tangent_id5.z; v3.w <- __input__.Tangent_id5.w; 
//   v4.x <- __input__.TexCoord_id6.x; v4.y <- __input__.TexCoord_id6.y; 
//   o3.x <- <VSMain return value>.TexCoord_id6.x; o3.y <- <VSMain return value>.TexCoord_id6.y; 
//   o2.x <- <VSMain return value>.Tangent_id5.x; o2.y <- <VSMain return value>.Tangent_id5.y; o2.z <- <VSMain return value>.Tangent_id5.z; o2.w <- <VSMain return value>.Tangent_id5.w; 
//   o1.x <- <VSMain return value>.Normal_id4.x; o1.y <- <VSMain return value>.Normal_id4.y; o1.z <- <VSMain return value>.Normal_id4.z; 
//   o0.x <- <VSMain return value>.ShadingPosition_id2.x; o0.y <- <VSMain return value>.ShadingPosition_id2.y; o0.z <- <VSMain return value>.ShadingPosition_id2.z; o0.w <- <VSMain return value>.ShadingPosition_id2.w
//
#line 85 "C:\Users\benox\Documents\vvvv\gamma\Exports\VVVVarkle\lib\log\shader_InstancedMeshTangentStreamOut_DrawFX_a6b9e87176d870fee62a4dea998388c0.hlsl"
ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r0.xyzw, v0.x, l(48), t0.xyzw  // r0.x <- iw._m03; r0.y <- iw._m13; r0.z <- iw._m23; r0.w <- iw._m33

#line 86
mov r1.xyz, v1.xyzx
mov r1.w, l(1.000000)
dp4 o0.w, r1.xyzw, r0.xyzw

#line 85
ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r0.xyzw, v0.x, l(0), t0.xyzw  // r0.x <- iw._m00; r0.y <- iw._m10; r0.z <- iw._m20; r0.w <- iw._m30

#line 86
dp4 o0.x, r1.xyzw, r0.xyzw

#line 85
ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r2.xyzw, v0.x, l(16), t0.xyzw  // r2.x <- iw._m01; r2.y <- iw._m11; r2.z <- iw._m21; r2.w <- iw._m31

#line 86
dp4 o0.y, r1.xyzw, r2.xyzw

#line 85
ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r3.xyzw, v0.x, l(32), t0.xyzw  // r3.x <- iw._m02; r3.y <- iw._m12; r3.z <- iw._m22; r3.w <- iw._m32

#line 86
dp4 o0.z, r1.xyzw, r3.xyzw

#line 87
dp3 o1.x, v2.xyzx, r0.xyzx

#line 88
dp3 o2.x, v3.xyzx, r0.xyzx

#line 87
dp3 o1.y, v2.xyzx, r2.xyzx

#line 88
dp3 o2.y, v3.xyzx, r2.xyzx

#line 87
dp3 o1.z, v2.xyzx, r3.xyzx

#line 88
dp3 o2.z, v3.xyzx, r3.xyzx

#line 95
mov o2.w, v3.w
mov o3.xy, v4.xyxx
ret 
// Approximately 19 instruction slots used
@G    Geometry => 7bd399dbb026176fce052c84edb94193
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TANGENT                  0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
gs_5_0
dcl_globalFlags refactoringAllowed
dcl_input_siv v[3][0].xyzw, position
dcl_input v[3][1].xyz
dcl_input v[3][2].xyzw
dcl_input v[3][3].xy
dcl_temps 1
dcl_inputprimitive triangle 
dcl_stream m0
dcl_outputtopology trianglestrip 
dcl_output_siv o0.xyzw, position
dcl_output o1.xyz
dcl_output o2.xyzw
dcl_output o3.xy
dcl_maxout 3
//
// Initial variable locations:
//   m0 <- triangleStream; 
//   v[0][0].x <- input[0].ShadingPosition_id2.x; v[0][0].y <- input[0].ShadingPosition_id2.y; v[0][0].z <- input[0].ShadingPosition_id2.z; v[0][0].w <- input[0].ShadingPosition_id2.w; 
//   v[0][1].x <- input[0].Normal_id4.x; v[0][1].y <- input[0].Normal_id4.y; v[0][1].z <- input[0].Normal_id4.z; 
//   v[0][2].x <- input[0].Tangent_id5.x; v[0][2].y <- input[0].Tangent_id5.y; v[0][2].z <- input[0].Tangent_id5.z; v[0][2].w <- input[0].Tangent_id5.w; 
//   v[0][3].x <- input[0].TexCoord_id6.x; v[0][3].y <- input[0].TexCoord_id6.y; 
//   v[1][0].x <- input[1].ShadingPosition_id2.x; v[1][0].y <- input[1].ShadingPosition_id2.y; v[1][0].z <- input[1].ShadingPosition_id2.z; v[1][0].w <- input[1].ShadingPosition_id2.w; 
//   v[1][1].x <- input[1].Normal_id4.x; v[1][1].y <- input[1].Normal_id4.y; v[1][1].z <- input[1].Normal_id4.z; 
//   v[1][2].x <- input[1].Tangent_id5.x; v[1][2].y <- input[1].Tangent_id5.y; v[1][2].z <- input[1].Tangent_id5.z; v[1][2].w <- input[1].Tangent_id5.w; 
//   v[1][3].x <- input[1].TexCoord_id6.x; v[1][3].y <- input[1].TexCoord_id6.y; 
//   v[2][0].x <- input[2].ShadingPosition_id2.x; v[2][0].y <- input[2].ShadingPosition_id2.y; v[2][0].z <- input[2].ShadingPosition_id2.z; v[2][0].w <- input[2].ShadingPosition_id2.w; 
//   v[2][1].x <- input[2].Normal_id4.x; v[2][1].y <- input[2].Normal_id4.y; v[2][1].z <- input[2].Normal_id4.z; 
//   v[2][2].x <- input[2].Tangent_id5.x; v[2][2].y <- input[2].Tangent_id5.y; v[2][2].z <- input[2].Tangent_id5.z; v[2][2].w <- input[2].Tangent_id5.w; 
//   v[2][3].x <- input[2].TexCoord_id6.x; v[2][3].y <- input[2].TexCoord_id6.y
//
#line 72 "C:\Users\benox\Documents\vvvv\gamma\Exports\VVVVarkle\lib\log\shader_InstancedMeshTangentStreamOut_DrawFX_a6b9e87176d870fee62a4dea998388c0.hlsl"
mov r0.x, l(0)  // r0.x <- i
loop 
  ige r0.y, r0.x, l(3)
  breakc_nz r0.y

#line 64
  mov o0.xyzw, v[r0.x + 0][0].xyzw
  mov o1.xyz, v[r0.x + 0][1].xyzx
  mov o2.xyzw, v[r0.x + 0][2].xyzw
  mov o3.xy, v[r0.x + 0][3].xyxx
  emit_stream m0

#line 75
  iadd r0.x, r0.x, l(1)
endloop 

#line 76
ret 
// Approximately 12 instruction slots used
***************************
*************************/
struct GS_STREAMS 
{
    float4 ShadingPosition_id2;
    float3 Normal_id4;
    float4 Tangent_id5;
    float2 TexCoord_id6;
};
struct GS_OUTPUT 
{
    float4 ShadingPosition_id2 : SV_Position;
    float3 Normal_id4 : NORMAL;
    float4 Tangent_id5 : TANGENT;
    float2 TexCoord_id6 : TEXCOORD;
};
struct GS_INPUT 
{
    float4 ShadingPosition_id2 : SV_Position;
    float3 Normal_id4 : NORMAL;
    float4 Tangent_id5 : TANGENT;
    float2 TexCoord_id6 : TEXCOORD;
};
struct VS_STREAMS 
{
    uint InstanceID_id1;
    float3 Position_id3;
    float3 Normal_id4;
    float4 Tangent_id5;
    float2 TexCoord_id6;
    float4 ShadingPosition_id2;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id2 : SV_Position;
    float3 Normal_id4 : NORMAL;
    float4 Tangent_id5 : TANGENT;
    float2 TexCoord_id6 : TEXCOORD;
};
struct VS_INPUT 
{
    uint InstanceID_id1 : SV_InstanceID;
    float3 Position_id3 : POSITION;
    float3 Normal_id4 : NORMAL;
    float4 Tangent_id5 : TANGENT;
    float2 TexCoord_id6 : TEXCOORD;
};
struct InstanceTransform 
{
    float4x4 Matrix;
};
StructuredBuffer<InstanceTransform> InstanceWorld_id0;
void AppendVertex_id0(inout GS_STREAMS streams, GS_INPUT In, inout TriangleStream<GS_OUTPUT> triangleStream)
{
    streams.ShadingPosition_id2 = In.ShadingPosition_id2;
    streams.Normal_id4 = In.Normal_id4;
    streams.Tangent_id5 = In.Tangent_id5;
    streams.TexCoord_id6 = In.TexCoord_id6;

    {
        GS_OUTPUT output = (GS_OUTPUT)0;
        output.ShadingPosition_id2 = streams.ShadingPosition_id2;
        output.Normal_id4 = streams.Normal_id4;
        output.Tangent_id5 = streams.Tangent_id5;
        output.TexCoord_id6 = streams.TexCoord_id6;
        triangleStream.Append(output);
    }
}
[maxvertexcount(3)]
void GSMain(triangle GS_INPUT input[3], inout TriangleStream<GS_OUTPUT> triangleStream)
{
    GS_STREAMS streams = (GS_STREAMS)0;

    for (int i = 0; i < 3; i++)
    {
        AppendVertex_id0(streams, input[i], triangleStream);
    }
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.InstanceID_id1 = __input__.InstanceID_id1;
    streams.Position_id3 = __input__.Position_id3;
    streams.Normal_id4 = __input__.Normal_id4;
    streams.Tangent_id5 = __input__.Tangent_id5;
    streams.TexCoord_id6 = __input__.TexCoord_id6;
    float4x4 iw = InstanceWorld_id0[streams.InstanceID_id1].Matrix;
    streams.ShadingPosition_id2 = mul(float4(streams.Position_id3.xyz, 1), iw);
    streams.Normal_id4 = mul(float4(streams.Normal_id4.xyz, 0), iw).xyz;
    streams.Tangent_id5 = float4(mul(float4(streams.Tangent_id5.xyz, 0), iw).xyz, streams.Tangent_id5.w);
    streams.TexCoord_id6 = streams.TexCoord_id6;
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id2 = streams.ShadingPosition_id2;
    __output__.Normal_id4 = streams.Normal_id4;
    __output__.Tangent_id5 = streams.Tangent_id5;
    __output__.TexCoord_id6 = streams.TexCoord_id6;
    return __output__;
}
